[[constraint]]
  name = "github.com/hashicorp/vault"
  version = "0.11.4"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/spacemonkeygo/openssl"

[prune]
  go-tests = true
  unused-packages = true
