---
vault_address: http://vault:8200
vault_token: keepsake-vault-client
vault_pki-path: pki
renewal_coefficient: 0.9
certificates:
  - cname: certset.keepsake.com
    altnames:
      - foo.keepsake.com
    vaultrole: keepsake
    ttl: 10m
    cert: docker/keepsake_client.crt
    key: docker/keepsake_client.key
    root: docker/root1.crt
    cmd: 'echo updated certset'
    ipaddresses:
      - "127.0.0.1"
      - "10.10.10.10"
    tests:
      cname: ""
      cacname: keepsake
      ttl: ""
  - cname: certset2.keepsake.com
    vaultrole: keepsake
    ttl: 10s
    cert: docker/keepsake_client2.crt
    key: docker/keepsake_client2.key
    root: docker/root2.crt
    cmd: 'echo updated certset2'
    ipaddresses:
      - "127.0.0.1"
    tests:
      cname: ""
      cacname: keepsake
      ttl: ""
  - cname: certset-bundle.keepsake.com
    vaultrole: keepsake
    ttl: 15s
    bundle: docker/keepsake_client_bundle.pem
    key: docker/keepsake_client.key
    cmd: 'echo updated bundle'
    ipaddresses:
      - "127.0.0.1"
    tests:
      cname: ""
      cacname: keepsake
      ttl: ""
 
